### ISSUE TITLE
please update ssl submodule and then release v3.14.2 so that libuhttpd builds with mbedtls 3.x

### ISSUE THREAD

**Issue by gstrauss** [zhaojh329/libuhttpd#26]
Please update src/ssl submodule and then release v3.14.2 so that libuhttpd builds with mbedtls 3.x.

https://github.com/zhaojh329/ssl already contains your patches to build that ssl repo with mbedtls 3.x, but libuhttpd submodule at src/ssl needs to be updated to pick up the changes.

Thank you.

**Comment by zhaojh329** [comment]
You can make a PR.

**Comment by gstrauss** [comment]
I created #27 to update the src/ssl submodule in libuhttpd.  Please review for inclusion in the next libuhttpd release, and then please release libuhttpd v3.14.2 so that libuhttpd builds with mbedtls 3.x.  Thank you.

**Comment by Neustradamus** [comment]
@zhaojh329: @gstrauss has done a PR, can you look?
- https://github.com/zhaojh329/libuhttpd/pull/27

**Comment by gstrauss** [comment]
@zhaojh329 thanks for merging #27 and, for this PR, laying down a new tag: `v3.14.2`

**Comment by Neustradamus** [comment]
Thanks to @gstrauss and @zhaojh329!
