### ISSUE TITLE
V2.2.2在openwrt交叉编译时找不到: liblua.so.5.1.5

### ISSUE THREAD

**Issue by kurbylee** [zhaojh329/libuhttpd#3]
当在openwrt的编译环境中，make package/libuhttpd/compile V=99时，产生找不到liblua.so的错误
#sudo make package/libuhttpd/compile V=99
.....
install -d -m0755 /home/ugreen/sdk1296/buildscripts/OpenWrt-ImageBuilder-rtd1295-mnas_emmc.Linux-x86_64/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-nossl/libuhttpd-2.2.2/ipkg-rtd1295/libuhttpd-nossl/usr/lib/
install -m0644 /home/ugreen/sdk1296/buildscripts/OpenWrt-ImageBuilder-rtd1295-mnas_emmc.Linux-x86_64/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-nossl/libuhttpd-2.2.2/ipkg-install/usr/lib/libuhttpd.so* /home/ugreen/sdk1296/buildscripts/OpenWrt-ImageBuilder-rtd1295-mnas_emmc.Linux-x86_64/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-nossl/libuhttpd-2.2.2/ipkg-rtd1295/libuhttpd-nossl/usr/lib/
find /home/ugreen/sdk1296/buildscripts/OpenWrt-ImageBuilder-rtd1295-mnas_emmc.Linux-x86_64/build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-nossl/libuhttpd-2.2.2/ipkg-rtd1295/libuhttpd-nossl -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package libuhttpd-nossl is missing dependencies for the following libraries:
liblua.so.5.1.5
Makefile:83: recipe for target '/home/ugreen/sdk1296/buildscripts/OpenWrt-ImageBuilder-rtd1295-mnas_emmc.Linux-x86_64/bin/rtd1295-glibc/packages/base/libuhttpd-nossl_2.2.2-1_rtd1295.ipk' failed
make[2]: *** [/home/ugreen/sdk1296/buildscripts/OpenWrt-ImageBuilder-rtd1295-mnas_emmc.Linux-x86_64/bin/rtd1295-glibc/packages/base/libuhttpd-nossl_2.2.2-1_rtd1295.ipk] Error 1
make[2]: Leaving directory '/home/ugreen/sdk1296/buildscripts/OpenWrt-ImageBuilder-rtd1295-mnas_emmc.Linux-x86_64/package/network/services/libuhttpd'
****package/Makefile:191: recipe for target 'package/network/services/libuhttpd/compile' failed
make[1]: *** [package/network/services/libuhttpd/compile] Error 2****
make[1]: Leaving directory '/home/ugreen/sdk1296/buildscripts/OpenWrt-ImageBuilder-rtd1295-mnas_emmc.Linux-x86_64'
/home/ugreen/sdk1296/buildscripts/OpenWrt-ImageBuilder-rtd1295-mnas_emmc.Linux-x86_64/include/toplevel.mk:198: recipe for target 'package/libuhttpd/compile' failed
make: *** [package/libuhttpd/compile] Error 2

**#find ./ -name liblua.so.***
./target/linux/rtd1295/image/image_file-r160868/tmp/rootfs/usr/lib/liblua.so.5.1.5
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/root-rtd1295/usr/lib/liblua.so.5.1.5
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/lua-5.1.5/ipkg-install/usr/lib/liblua.so.5.1.5
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/lua-5.1.5/ipkg-rtd1295/liblua/usr/lib/liblua.so.5.1.5
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/lua-5.1.5/src/liblua.so.5.1.5
./staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/root-rtd1295/usr/lib/liblua.so.5.1.5
./staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/usr/lib/liblua.so.5.1.5

**find ./ -name libuhttpd.so.***
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-nossl/libuhttpd-1.0.4/ipkg-install/usr/lib/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-nossl/libuhttpd-1.0.4/ipkg-rtd1295/libuhttpd-nossl/usr/lib/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-nossl/libuhttpd-1.0.4/src/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-nossl/libuhttpd-2.2.2/ipkg-install/usr/lib/libuhttpd.so.2.2.2
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-nossl/libuhttpd-2.2.2/ipkg-rtd1295/libuhttpd-nossl/usr/lib/libuhttpd.so.2.2.2
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-nossl/libuhttpd-2.2.2/src/libuhttpd.so.2.2.2
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-mbedtls/libuhttpd-1.0.4/ipkg-install/usr/lib/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-mbedtls/libuhttpd-1.0.4/ipkg-rtd1295/libuhttpd-mbedtls/usr/lib/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-mbedtls/libuhttpd-1.0.4/src/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-openssl/libuhttpd-1.0.4/ipkg-install/usr/lib/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-openssl/libuhttpd-1.0.4/ipkg-rtd1295/libuhttpd-openssl/usr/lib/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-openssl/libuhttpd-1.0.4/src/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-openssl/libuhttpd-2.2.2/src/libuhttpd.so.2.2.2
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-wolfssl/libuhttpd-1.0.4/ipkg-install/usr/lib/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-wolfssl/libuhttpd-1.0.4/ipkg-rtd1295/libuhttpd-wolfssl/usr/lib/libuhttpd.so.1.0.4
./build_dir/target-aarch64_cortex-a53+neon_glibc-2.19/libuhttpd-wolfssl/libuhttpd-1.0.4/src/libuhttpd.so.1.0.4
./staging_dir/target-aarch64_cortex-a53+neon_glibc-2.19/root-rtd1295/usr/lib/libuhttpd.so.1.0.4
ugreen@ugreen-PowerEdge-T140:~/sdk1296/buildscripts/OpenWrt-ImageBuilder-rtd1295-mnas_emmc.Linux-x86_64$

**Comment by zhaojh329** [comment]
请请使用最新版本
